package ru.nsu.kinolist.bot.util;

public enum BotState {
    START,
    SHOW_MAIN_MENU,
    SHOW_HELP,
    SHOW_PLAYLISTS_MENU,
    IDLE,
    WISHLIST,
    TRACKEDLIST,
    WATCHEDLIST,
    WISHLIST_ADD,
    WISHLIST_TRANSFER,
    WISHLIST_REMOVE,
    WATCHEDLIST_ADD,
    WATCHEDLIST_REMOVE,
    TRACKEDLIST_ADD,
    TRACKED_REMOVE,
}
